[tool.poetry]
name = "testproject"
version = "0.1.0"
description = ""
authors = ["Roberto <roberto.patron@justeattakeaway.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
pandas = "^2.1.4"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
